# Generated by Django 5.2.5 on 2025-09-04 15:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0004_profile_old_cart'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='old_cart',
            field=models.TextField(blank=True, null=True),
        ),
    ]
